#!/usr/bin/env bash
# www/measure-sizes.sh — measure what each grammar costs a linked mmz binary.
#
# The docs argue that a grammar is not small, and that argument is only worth
# reading if the numbers behind it are measured rather than remembered. They
# were hand-typed once and had already rotted by the next release: the page
# claimed a 3.5 MB binary that no build had produced since the jq and ast-grep
# engines landed. This script is the fix — measure once, deliberately, and
# commit the result as www/sizes.yaml for the docs to READ.
#
# Why a committed artifact rather than another www/generate-facts.sh producer:
# that script runs inside `just check`, and this one links the binary THIRTY
# times. A fact whose measurement costs an hour cannot be derived on every
# docs build; it has to be derived on demand and reviewed into the tree. The
# outdatty `binary-size` group is what schedules the re-run — it fails the gate
# when Cargo.toml or Cargo.lock moves under a recorded measurement, and
# generate-facts.sh separately refuses a measurement whose grammar set no
# longer matches the crate's features.
#
# Run it with `just measure-sizes`. Expect ~40 minutes cold: every build is a
# full LTO link of one binary, and the release profile this repo ships (`lto`,
# `codegen-units = 1`, `strip`) is exactly the profile the claim is about.
#
# The measurements, all on the host target:
#
#   none      `--no-default-features`, the grammar-free baseline. Not a build
#             anyone ships; it exists so a per-grammar cost can be a difference
#             against something, and so `rust` can be measured at all — it is in
#             `default`, so a delta against `default` would price it at zero.
#   default   what `cargo install mmz` gives you (`lang-rust`).
#   full      `--features lang-all`, the `mmz-full-<target>` release asset.
#   <lang>    `--no-default-features --features lang-<lang>`, minus `none`.
#
# Per-grammar costs do NOT sum to `full - none`: the grammars share a
# tree-sitter runtime that each single-grammar build also pays for. Both
# numbers are recorded so a reader can have the one they asked for.
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$SCRIPT_DIR/sizes.yaml"

cd "$REPO"

# A target directory of its own. Thirty feature permutations through the shared
# one would evict the dev build's artifacts and leave the next `cargo test`
# recompiling from cold — and www/generate.sh's `target/release/mmz`, which the
# docs captures run, would be silently replaced by whichever flavour this script
# linked last.
TARGET_DIR="$REPO/target/size-measure"
BIN="$TARGET_DIR/release/mmz"

# The grammar list comes from the crate's own features, never from a list here:
# a `lang-` feature added to Cargo.toml must reach this script without anyone
# remembering to edit it. The rule for what counts as one lives in
# www/lang-features.jq, shared with www/generate-facts.sh — which checks this
# script's output against the same list, and could not do so honestly by
# deriving it a second way.
readarray -t GRAMMARS < <(
  cargo metadata --format-version 1 --no-deps \
    | jq -r -f "$SCRIPT_DIR/lang-features.jq" \
    | jq -r '.[]'
)
if [ "${#GRAMMARS[@]}" -eq 0 ]; then
  echo "measure-sizes.sh: no lang-* features found in Cargo.toml" >&2
  exit 1
fi

# Build one flavour and print the linked size in bytes. Cargo's own output goes
# to stderr so stdout carries the number alone.
measure() {
  local label="$1"
  shift
  echo "measure-sizes.sh: building $label ..." >&2
  cargo build --release --target-dir "$TARGET_DIR" "$@" >&2
  if [ ! -f "$BIN" ]; then
    echo "measure-sizes.sh: $label produced no binary at $BIN" >&2
    return 1
  fi
  stat -c %s "$BIN"
}

RUSTC_VERSION="$(rustc --version)"
HOST="$(rustc -vV | sed -n 's/^host: //p')"
CRATE_VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -1)"

NONE=$(measure none --no-default-features)
DEFAULT=$(measure default)
FULL=$(measure full --features lang-all)

# Written through a temp file and moved into place, the same discipline
# www/generate-facts.sh uses: a run killed halfway through its thirty builds
# leaves the previous complete measurement in the tree rather than a file
# holding four grammars and claiming to hold twenty-seven.
TMP="$OUT.tmp.$$"
trap 'rm -f "$TMP"' EXIT

cat >"$TMP" <<YAML
# www/sizes.yaml — GENERATED by www/measure-sizes.sh; do not hand-edit.
#
# Every byte figure the docs quote about binary size is read from this file
# (www/generate-facts.sh -> www/generated/sizes.json -> www/utils/sizes.typ), so
# a number in prose is a number something measured. Re-measure with
# \`just measure-sizes\`; \`just outdatty-check\` fails until a measurement is
# re-confirmed against the Cargo.toml and Cargo.lock it was taken under.
#
# Sizes are bytes, as \`stat\` reports them. The docs render them in decimal
# MB/KB (1 MB = 1000 KB), which is the convention GitHub's release assets and
# every "how big is the download" question use.
#
# \`grammars\` prices each grammar as its own delta against \`none\`, so the
# entries are comparable with each other. They do not sum to
# \`builds.full - builds.none\`; see measure-sizes.sh's header.
measured:
  crate_version: "$CRATE_VERSION"
  host: "$HOST"
  profile: release
  rustc: "$RUSTC_VERSION"

builds:
  none: $NONE
  default: $DEFAULT
  full: $FULL

grammars:
YAML

for lang in "${GRAMMARS[@]}"; do
  size=$(measure "lang-$lang" --no-default-features --features "lang-$lang")
  printf '  %s: %s\n' "$lang" "$((size - NONE))" >>"$TMP"
done

# Refuse to install a measurement that is not parseable, or that lost a grammar
# between the header and the loop — the file is committed and read by the docs
# build, so a malformed one fails a render three steps away from its cause.
if ! yq -e '.' "$TMP" >/dev/null 2>&1; then
  echo "measure-sizes.sh: refusing to install malformed $OUT" >&2
  exit 1
fi
recorded=$(yq -r '.grammars | keys | length' "$TMP")
if [ "$recorded" -ne "${#GRAMMARS[@]}" ]; then
  echo "measure-sizes.sh: measured ${#GRAMMARS[@]} grammars but recorded $recorded" >&2
  exit 1
fi

mv -f "$TMP" "$OUT"
echo "measure-sizes.sh: ${#GRAMMARS[@]} grammars measured into $OUT"
